language: ruby
rvm:
  - 2.4.1
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver
env:
  - CHROME_DRIVER_PATH=/tmp/chromedriver
script:
  - chromedriver
  - xvfb-run bundle exec rails test