language: ruby
rvm:
  - 2.4.1
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - chromium-chromedriver
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -O /tmp/chromedriver
  - chmod 777 /tmp/chromedriver
env:
  - CHROME_DRIVER_PATH=/tmp/chromedriver
script:
  - xvfb-run bundle exec rails test