language: ruby
rvm:
  - 2.4.1
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - xvfb-run bundle exec rails test